steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/simran-khuranagmail/gcp-cd-codelab"]
    env: ["PROJECT_ROOT=github.com/simran-khuranagmail/gcp-cd-codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/manasvi-225210/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/manasvi-225210/gcp-cd-codelab:$REVISION_ID"
